/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package rubike.src;

import java.util.Stack;

/**
 *
 * @author François
 */
public class Fenetre extends javax.swing.JFrame {

	private Cube c;
	private Shuffler s;
	private Stack<Move> mv;
	
	/**
	 * Creates new form Fenetre
	 */
	public Fenetre() {
		initComponents();
		c = new Cube();
		s = new Shuffler(c);
		mv = new Stack<>();
		
		updateCubeDisplay();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        CubePane = new javax.swing.JPanel();
        Face1 = new javax.swing.JPanel();
        Face11 = new javax.swing.JPanel();
        Face12 = new javax.swing.JPanel();
        Face13 = new javax.swing.JPanel();
        Face14 = new javax.swing.JPanel();
        Face2 = new javax.swing.JPanel();
        Face21 = new javax.swing.JPanel();
        Face22 = new javax.swing.JPanel();
        Face23 = new javax.swing.JPanel();
        Face24 = new javax.swing.JPanel();
        Face3 = new javax.swing.JPanel();
        Face31 = new javax.swing.JPanel();
        Face32 = new javax.swing.JPanel();
        Face33 = new javax.swing.JPanel();
        Face34 = new javax.swing.JPanel();
        Face4 = new javax.swing.JPanel();
        Face41 = new javax.swing.JPanel();
        Face42 = new javax.swing.JPanel();
        Face43 = new javax.swing.JPanel();
        Face44 = new javax.swing.JPanel();
        Face5 = new javax.swing.JPanel();
        Face51 = new javax.swing.JPanel();
        Face52 = new javax.swing.JPanel();
        Face53 = new javax.swing.JPanel();
        Face54 = new javax.swing.JPanel();
        Face6 = new javax.swing.JPanel();
        Face61 = new javax.swing.JPanel();
        Face62 = new javax.swing.JPanel();
        Face63 = new javax.swing.JPanel();
        Face64 = new javax.swing.JPanel();
        ShufflePane = new javax.swing.JPanel();
        ShuffleOrder = new javax.swing.JSpinner();
        ShuffleButton = new javax.swing.JButton();
        SolverPane = new javax.swing.JPanel();
        NextMoveLabel = new javax.swing.JLabel();
        NextMove = new javax.swing.JLabel();
        ControlsPane = new javax.swing.JPanel();
        F = new javax.swing.JButton();
        T = new javax.swing.JButton();
        R = new javax.swing.JButton();
        Rr = new javax.swing.JButton();
        Tr = new javax.swing.JButton();
        Fr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pocket Cube Solver");
        setResizable(false);

        Title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Title.setText("Pocket Cube solver");

        CubePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        Face1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Face11Layout = new javax.swing.GroupLayout(Face11);
        Face11.setLayout(Face11Layout);
        Face11Layout.setHorizontalGroup(
            Face11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face11Layout.setVerticalGroup(
            Face11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face12Layout = new javax.swing.GroupLayout(Face12);
        Face12.setLayout(Face12Layout);
        Face12Layout.setHorizontalGroup(
            Face12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face12Layout.setVerticalGroup(
            Face12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face13Layout = new javax.swing.GroupLayout(Face13);
        Face13.setLayout(Face13Layout);
        Face13Layout.setHorizontalGroup(
            Face13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face13Layout.setVerticalGroup(
            Face13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face14Layout = new javax.swing.GroupLayout(Face14);
        Face14.setLayout(Face14Layout);
        Face14Layout.setHorizontalGroup(
            Face14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face14Layout.setVerticalGroup(
            Face14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face1Layout = new javax.swing.GroupLayout(Face1);
        Face1.setLayout(Face1Layout);
        Face1Layout.setHorizontalGroup(
            Face1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Face1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Face1Layout.createSequentialGroup()
                        .addComponent(Face14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Face1Layout.createSequentialGroup()
                        .addComponent(Face11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Face1Layout.setVerticalGroup(
            Face1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Face1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Face1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Face2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Face21Layout = new javax.swing.GroupLayout(Face21);
        Face21.setLayout(Face21Layout);
        Face21Layout.setHorizontalGroup(
            Face21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face21Layout.setVerticalGroup(
            Face21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face22Layout = new javax.swing.GroupLayout(Face22);
        Face22.setLayout(Face22Layout);
        Face22Layout.setHorizontalGroup(
            Face22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face22Layout.setVerticalGroup(
            Face22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face23Layout = new javax.swing.GroupLayout(Face23);
        Face23.setLayout(Face23Layout);
        Face23Layout.setHorizontalGroup(
            Face23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face23Layout.setVerticalGroup(
            Face23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face24Layout = new javax.swing.GroupLayout(Face24);
        Face24.setLayout(Face24Layout);
        Face24Layout.setHorizontalGroup(
            Face24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face24Layout.setVerticalGroup(
            Face24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face2Layout = new javax.swing.GroupLayout(Face2);
        Face2.setLayout(Face2Layout);
        Face2Layout.setHorizontalGroup(
            Face2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Face2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Face2Layout.createSequentialGroup()
                        .addComponent(Face24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Face2Layout.createSequentialGroup()
                        .addComponent(Face21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Face2Layout.setVerticalGroup(
            Face2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Face2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Face2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Face3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Face31Layout = new javax.swing.GroupLayout(Face31);
        Face31.setLayout(Face31Layout);
        Face31Layout.setHorizontalGroup(
            Face31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face31Layout.setVerticalGroup(
            Face31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face32Layout = new javax.swing.GroupLayout(Face32);
        Face32.setLayout(Face32Layout);
        Face32Layout.setHorizontalGroup(
            Face32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face32Layout.setVerticalGroup(
            Face32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face33Layout = new javax.swing.GroupLayout(Face33);
        Face33.setLayout(Face33Layout);
        Face33Layout.setHorizontalGroup(
            Face33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face33Layout.setVerticalGroup(
            Face33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face34Layout = new javax.swing.GroupLayout(Face34);
        Face34.setLayout(Face34Layout);
        Face34Layout.setHorizontalGroup(
            Face34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face34Layout.setVerticalGroup(
            Face34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face3Layout = new javax.swing.GroupLayout(Face3);
        Face3.setLayout(Face3Layout);
        Face3Layout.setHorizontalGroup(
            Face3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Face3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Face3Layout.createSequentialGroup()
                        .addComponent(Face34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Face3Layout.createSequentialGroup()
                        .addComponent(Face31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Face3Layout.setVerticalGroup(
            Face3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Face3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Face3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Face4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Face41Layout = new javax.swing.GroupLayout(Face41);
        Face41.setLayout(Face41Layout);
        Face41Layout.setHorizontalGroup(
            Face41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face41Layout.setVerticalGroup(
            Face41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face42Layout = new javax.swing.GroupLayout(Face42);
        Face42.setLayout(Face42Layout);
        Face42Layout.setHorizontalGroup(
            Face42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face42Layout.setVerticalGroup(
            Face42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face43Layout = new javax.swing.GroupLayout(Face43);
        Face43.setLayout(Face43Layout);
        Face43Layout.setHorizontalGroup(
            Face43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face43Layout.setVerticalGroup(
            Face43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face44Layout = new javax.swing.GroupLayout(Face44);
        Face44.setLayout(Face44Layout);
        Face44Layout.setHorizontalGroup(
            Face44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face44Layout.setVerticalGroup(
            Face44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face4Layout = new javax.swing.GroupLayout(Face4);
        Face4.setLayout(Face4Layout);
        Face4Layout.setHorizontalGroup(
            Face4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Face4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Face4Layout.createSequentialGroup()
                        .addComponent(Face44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Face4Layout.createSequentialGroup()
                        .addComponent(Face41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Face4Layout.setVerticalGroup(
            Face4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Face4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Face4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Face5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Face51Layout = new javax.swing.GroupLayout(Face51);
        Face51.setLayout(Face51Layout);
        Face51Layout.setHorizontalGroup(
            Face51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face51Layout.setVerticalGroup(
            Face51Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face52Layout = new javax.swing.GroupLayout(Face52);
        Face52.setLayout(Face52Layout);
        Face52Layout.setHorizontalGroup(
            Face52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face52Layout.setVerticalGroup(
            Face52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face53Layout = new javax.swing.GroupLayout(Face53);
        Face53.setLayout(Face53Layout);
        Face53Layout.setHorizontalGroup(
            Face53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face53Layout.setVerticalGroup(
            Face53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face54Layout = new javax.swing.GroupLayout(Face54);
        Face54.setLayout(Face54Layout);
        Face54Layout.setHorizontalGroup(
            Face54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face54Layout.setVerticalGroup(
            Face54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face5Layout = new javax.swing.GroupLayout(Face5);
        Face5.setLayout(Face5Layout);
        Face5Layout.setHorizontalGroup(
            Face5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Face5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Face5Layout.createSequentialGroup()
                        .addComponent(Face54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Face5Layout.createSequentialGroup()
                        .addComponent(Face51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Face5Layout.setVerticalGroup(
            Face5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Face5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Face5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Face6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout Face61Layout = new javax.swing.GroupLayout(Face61);
        Face61.setLayout(Face61Layout);
        Face61Layout.setHorizontalGroup(
            Face61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face61Layout.setVerticalGroup(
            Face61Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face62Layout = new javax.swing.GroupLayout(Face62);
        Face62.setLayout(Face62Layout);
        Face62Layout.setHorizontalGroup(
            Face62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face62Layout.setVerticalGroup(
            Face62Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face63Layout = new javax.swing.GroupLayout(Face63);
        Face63.setLayout(Face63Layout);
        Face63Layout.setHorizontalGroup(
            Face63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face63Layout.setVerticalGroup(
            Face63Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face64Layout = new javax.swing.GroupLayout(Face64);
        Face64.setLayout(Face64Layout);
        Face64Layout.setHorizontalGroup(
            Face64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        Face64Layout.setVerticalGroup(
            Face64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Face6Layout = new javax.swing.GroupLayout(Face6);
        Face6.setLayout(Face6Layout);
        Face6Layout.setHorizontalGroup(
            Face6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Face6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Face6Layout.createSequentialGroup()
                        .addComponent(Face64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Face6Layout.createSequentialGroup()
                        .addComponent(Face61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Face6Layout.setVerticalGroup(
            Face6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Face6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Face6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Face6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CubePaneLayout = new javax.swing.GroupLayout(CubePane);
        CubePane.setLayout(CubePaneLayout);
        CubePaneLayout.setHorizontalGroup(
            CubePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubePaneLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(Face5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CubePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CubePaneLayout.createSequentialGroup()
                        .addComponent(Face3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Face6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Face4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CubePaneLayout.setVerticalGroup(
            CubePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CubePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Face1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Face2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CubePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Face3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Face6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Face4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ShuffleOrder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ShuffleOrder.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        ShuffleButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ShuffleButton.setText("Shuffle");
        ShuffleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShuffleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShufflePaneLayout = new javax.swing.GroupLayout(ShufflePane);
        ShufflePane.setLayout(ShufflePaneLayout);
        ShufflePaneLayout.setHorizontalGroup(
            ShufflePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShufflePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShuffleOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(ShufflePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShuffleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ShufflePaneLayout.setVerticalGroup(
            ShufflePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShufflePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ShuffleOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NextMoveLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NextMoveLabel.setText("Next move");

        NextMove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout SolverPaneLayout = new javax.swing.GroupLayout(SolverPane);
        SolverPane.setLayout(SolverPaneLayout);
        SolverPaneLayout.setHorizontalGroup(
            SolverPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolverPaneLayout.createSequentialGroup()
                .addGroup(SolverPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolverPaneLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(NextMoveLabel))
                    .addGroup(SolverPaneLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(NextMove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SolverPaneLayout.setVerticalGroup(
            SolverPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolverPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NextMoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextMove, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });

        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });

        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });

        Rr.setText("R'");
        Rr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RrActionPerformed(evt);
            }
        });

        Tr.setText("T'");
        Tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrActionPerformed(evt);
            }
        });

        Fr.setText("F'");
        Fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlsPaneLayout = new javax.swing.GroupLayout(ControlsPane);
        ControlsPane.setLayout(ControlsPaneLayout);
        ControlsPaneLayout.setHorizontalGroup(
            ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ControlsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Fr, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tr, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rr, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        ControlsPaneLayout.setVerticalGroup(
            ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(ControlsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Title)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ControlsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SolverPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShufflePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(CubePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShufflePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SolverPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ControlsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CubePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void updateCubeDisplay()
	{
		Face11.setBackground(c.getColor(0, 0));
		Face12.setBackground(c.getColor(0, 1));
		Face13.setBackground(c.getColor(0, 2));
		Face14.setBackground(c.getColor(0, 3));
		Face21.setBackground(c.getColor(1, 0));
		Face22.setBackground(c.getColor(1, 1));
		Face23.setBackground(c.getColor(1, 2));
		Face24.setBackground(c.getColor(1, 3));
		Face31.setBackground(c.getColor(2, 0));
		Face32.setBackground(c.getColor(2, 1));
		Face33.setBackground(c.getColor(2, 2));
		Face34.setBackground(c.getColor(2, 3));
		Face41.setBackground(c.getColor(3, 0));
		Face42.setBackground(c.getColor(3, 1));
		Face43.setBackground(c.getColor(3, 2));
		Face44.setBackground(c.getColor(3, 3));
		Face51.setBackground(c.getColor(4, 0));
		Face52.setBackground(c.getColor(4, 1));
		Face53.setBackground(c.getColor(4, 2));
		Face54.setBackground(c.getColor(4, 3));
		Face61.setBackground(c.getColor(5, 0));
		Face62.setBackground(c.getColor(5, 1));
		Face63.setBackground(c.getColor(5, 2));
		Face64.setBackground(c.getColor(5, 3));
	}
	
    private void ShuffleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShuffleButtonActionPerformed
		s.shuffle((Integer) ShuffleOrder.getValue());
		mv.addAll(s.getMoves());
		try
		{
			NextMove.setText(mv.pop().name());
		}
		catch (Exception e)
		{
			NextMove.setText("");
		}
		c = s.getCube();
		updateCubeDisplay();
    }//GEN-LAST:event_ShuffleButtonActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
		c.F();
		if(NextMove.getText().equals("F"))
		{
			try
			{
				NextMove.setText(mv.pop().name());
			}
			catch (Exception e)
			{
				NextMove.setText("");
			}
		}
		else
		{
			mv.add(new Move(NextMove.getText()));
			NextMove.setText("F'");
		}
		updateCubeDisplay();
    }//GEN-LAST:event_FActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
		c.T();
		if(NextMove.getText().equals("T"))
		{
			try
			{
				NextMove.setText(mv.pop().name());
			}
			catch (Exception e)
			{
				NextMove.setText("");
			}
		}
		else
		{
			mv.add(new Move(NextMove.getText()));
			NextMove.setText("T'");
		}
		updateCubeDisplay();
    }//GEN-LAST:event_TActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
		c.R();
		if(NextMove.getText().equals("R"))
		{
			try
			{
				NextMove.setText(mv.pop().name());
			}
			catch (Exception e)
			{
				NextMove.setText("");
			}
		}
		else
		{
			mv.add(new Move(NextMove.getText()));
			NextMove.setText("R'");
		}
		updateCubeDisplay();
    }//GEN-LAST:event_RActionPerformed

    private void FrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrActionPerformed
		c.Fr();
		if(NextMove.getText().equals("F'"))
		{
			try
			{
				NextMove.setText(mv.pop().name());
			}
			catch (Exception e)
			{
				NextMove.setText("");
			}
		}
		else
		{
			mv.add(new Move(NextMove.getText()));
			NextMove.setText("F");
		}
		updateCubeDisplay();
    }//GEN-LAST:event_FrActionPerformed

    private void TrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrActionPerformed
		c.Tr();
		if(NextMove.getText().equals("T'"))
		{
			try
			{
				NextMove.setText(mv.pop().name());
			}
			catch (Exception e)
			{
				NextMove.setText("");
			}
		}
		else
		{
			mv.add(new Move(NextMove.getText()));
			NextMove.setText("T");
		}
		updateCubeDisplay();
    }//GEN-LAST:event_TrActionPerformed

    private void RrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RrActionPerformed
		c.Rr();
		if(NextMove.getText().equals("R'"))
		{
			try
			{
				NextMove.setText(mv.pop().name());
			}
			catch (Exception e)
			{
				NextMove.setText("");
			}
		}
		else
		{
			mv.add(new Move(NextMove.getText()));
			NextMove.setText("R");
		}
		updateCubeDisplay();
    }//GEN-LAST:event_RrActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Fenetre().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlsPane;
    private javax.swing.JPanel CubePane;
    private javax.swing.JButton F;
    private javax.swing.JPanel Face1;
    private javax.swing.JPanel Face11;
    private javax.swing.JPanel Face12;
    private javax.swing.JPanel Face13;
    private javax.swing.JPanel Face14;
    private javax.swing.JPanel Face2;
    private javax.swing.JPanel Face21;
    private javax.swing.JPanel Face22;
    private javax.swing.JPanel Face23;
    private javax.swing.JPanel Face24;
    private javax.swing.JPanel Face3;
    private javax.swing.JPanel Face31;
    private javax.swing.JPanel Face32;
    private javax.swing.JPanel Face33;
    private javax.swing.JPanel Face34;
    private javax.swing.JPanel Face4;
    private javax.swing.JPanel Face41;
    private javax.swing.JPanel Face42;
    private javax.swing.JPanel Face43;
    private javax.swing.JPanel Face44;
    private javax.swing.JPanel Face5;
    private javax.swing.JPanel Face51;
    private javax.swing.JPanel Face52;
    private javax.swing.JPanel Face53;
    private javax.swing.JPanel Face54;
    private javax.swing.JPanel Face6;
    private javax.swing.JPanel Face61;
    private javax.swing.JPanel Face62;
    private javax.swing.JPanel Face63;
    private javax.swing.JPanel Face64;
    private javax.swing.JButton Fr;
    private javax.swing.JLabel NextMove;
    private javax.swing.JLabel NextMoveLabel;
    private javax.swing.JButton R;
    private javax.swing.JButton Rr;
    private javax.swing.JButton ShuffleButton;
    private javax.swing.JSpinner ShuffleOrder;
    private javax.swing.JPanel ShufflePane;
    private javax.swing.JPanel SolverPane;
    private javax.swing.JButton T;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Tr;
    // End of variables declaration//GEN-END:variables
}
